{{- if .Values.resources.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "imgproxy.serviceAccountName" $ }}
  labels:
    imgproxy: "true"
    {{- range $key, $val := ($.Values.resources.common.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- if or .Values.resources.serviceAccount.annotations .Values.features.aws.iamRoleName }}
  annotations:
    {{- with .Values.resources.serviceAccount }}
    {{- if .annotations }}
    {{- .annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Values.features.aws }}
    {{- if and .enabled .iamRoleName }}
    {{ include "aws.iamRoleAnnotation" $ }}
    {{- end }}
  {{- end }}
{{- end }}