name: check-helm-chart
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: imgproxy-helm/

      - name: Setup Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Helm Linter
        run: helm lint imgproxy-helm/imgproxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
